package model

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// writeJSONL writes one line per value: strings are written as is (to
// simulate corrupt lines), anything else is JSON encoded.
func writeJSONL(t *testing.T, path string, lines ...any) {
	t.Helper()
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
	var b strings.Builder
	for _, l := range lines {
		if s, ok := l.(string); ok {
			b.WriteString(s)
		} else {
			buf, err := json.Marshal(l)
			require.NoError(t, err)
			b.Write(buf)
		}
		b.WriteString("\n")
	}
	require.NoError(t, os.WriteFile(path, []byte(b.String()), 0o644))
}

type obj = map[string]any

func claudeTS(min, sec int) string {
	return time.Date(2026, 9, 10, 10, min, sec, 0, time.UTC).Format("2006-01-02T15:04:05.000Z")
}

func claudeUser(session, uuid, ts string, content any, extra obj) obj {
	l := obj{
		"type": "user", "uuid": uuid, "sessionId": session, "timestamp": ts,
		"cwd": "/tmp/proj", "version": "2.1.0",
		"message": obj{"role": "user", "content": content},
	}
	for k, v := range extra {
		l[k] = v
	}
	return l
}

func claudeAssistant(session, uuid, ts, msgID, reqID string, blocks []any, usage obj, extra obj) obj {
	l := obj{
		"type": "assistant", "uuid": uuid, "sessionId": session, "timestamp": ts,
		"cwd": "/tmp/proj", "version": "2.1.0", "requestId": reqID,
		"message": obj{"id": msgID, "model": "claude-sonnet-4-5", "role": "assistant", "content": blocks, "usage": usage},
	}
	for k, v := range extra {
		l[k] = v
	}
	return l
}

func usage(in, out, cacheCreate, cacheRead int) obj {
	return obj{"input_tokens": in, "output_tokens": out, "cache_creation_input_tokens": cacheCreate, "cache_read_input_tokens": cacheRead}
}

func sessionByID(t *testing.T, res *BackfillParseResult, id string) *BackfillSession {
	t.Helper()
	for _, s := range res.Sessions {
		if s.ID == id {
			return s
		}
	}
	t.Fatalf("session %s not found", id)
	return nil
}

func eventsOfType(s *BackfillSession, eventType string) []AICodeBackfillEvent {
	var out []AICodeBackfillEvent
	for _, e := range s.Events {
		if e.EventType == eventType {
			out = append(out, e)
		}
	}
	return out
}

func writeClaudeFixtures(t *testing.T) (string, string) {
	root := t.TempDir()
	projects := filepath.Join(root, "projects")
	text := func(s string) obj { return obj{"type": "text", "text": s} }

	writeJSONL(t, filepath.Join(projects, "-tmp-proj", "sess-a.jsonl"),
		obj{"type": "queue-operation", "operation": "enqueue", "timestamp": claudeTS(0, 0), "sessionId": "sess-a"},
		claudeUser("sess-a", "u1", claudeTS(0, 0), "Fix the bug", obj{"origin": obj{"kind": "human"}}),
		// One API response written as two lines; the first carries partial usage.
		claudeAssistant("sess-a", "a1", claudeTS(0, 5), "msg_1", "req_1",
			[]any{obj{"type": "thinking", "thinking": "..."}}, usage(10, 5, 100, 1000), nil),
		claudeAssistant("sess-a", "a2", claudeTS(0, 6), "msg_1", "req_1",
			[]any{obj{"type": "tool_use", "id": "toolu_1", "name": "Edit", "input": obj{"file_path": "/tmp/proj/a.go", "old_string": "secret"}}},
			usage(10, 50, 100, 1000), nil),
		claudeUser("sess-a", "u-r1", claudeTS(0, 10),
			[]any{obj{"type": "tool_result", "tool_use_id": "toolu_1", "is_error": true, "content": "file changed"}},
			obj{"toolUseResult": "Error: file changed"}),
		claudeAssistant("sess-a", "a3", claudeTS(0, 12), "msg_2", "req_2", []any{text("Done.")}, usage(3, 7, 0, 1100), obj{"costUSD": 0.01}),
		claudeUser("sess-a", "u2", claudeTS(0, 13), "Caveat: messages below were generated by local commands", obj{"isMeta": true}),
		claudeUser("sess-a", "u3", claudeTS(0, 14), "<local-command-stdout>ok</local-command-stdout>", nil),
		claudeUser("sess-a", "u4", claudeTS(0, 15), []any{text("[Request interrupted by user]")}, nil),
		claudeUser("sess-a", "u5", claudeTS(0, 16), "<task-notification>agent finished</task-notification>", obj{"origin": obj{"kind": "task-notification"}}),
		obj{
			"type": "assistant", "uuid": "a4", "sessionId": "sess-a", "timestamp": claudeTS(0, 17),
			"message": obj{"id": "msg_syn", "model": claudeSyntheticModel, "content": []any{text("No response requested.")}, "usage": usage(0, 0, 0, 0)},
		},
		obj{
			"type": "assistant", "uuid": "a5", "sessionId": "sess-a", "timestamp": claudeTS(0, 18), "isApiErrorMessage": true,
			"message": obj{"id": "msg_err", "model": claudeSyntheticModel, "content": []any{text("API Error: 529 overloaded")}, "usage": usage(0, 0, 0, 0)},
		},
		claudeUser("sess-a", "u6", claudeTS(1, 0),
			"<command-name>/review</command-name>\n<command-message>review</command-message>\n<command-args>PR 12</command-args>",
			obj{"origin": obj{"kind": "human"}}),
		`{"type":"assistant","truncated`,
		claudeAssistant("sess-a", "a6", claudeTS(1, 5), "msg_3", "req_3",
			[]any{obj{"type": "tool_use", "id": "toolu_2", "name": "Bash", "input": obj{"command": "export TOKEN=abc"}}}, usage(5, 5, 0, 2000), nil),
		claudeUser("sess-a", "u-r2", claudeTS(1, 9),
			[]any{obj{"type": "tool_result", "tool_use_id": "toolu_2", "content": "ok"}},
			obj{"toolUseResult": obj{"stdout": "ok", "durationMs": 1234}}),
	)

	// A subagent transcript: lines carry the parent session and isSidechain.
	writeJSONL(t, filepath.Join(projects, "-tmp-proj", "sess-a", "subagents", "agent-x.jsonl"),
		claudeUser("sess-a", "sub-u1", claudeTS(1, 20), "Explore the repo", obj{"isSidechain": true}),
		claudeAssistant("sess-a", "sub-a1", claudeTS(1, 25), "msg_5", "req_5", []any{text("Found it")}, usage(20, 30, 0, 0), obj{"isSidechain": true}),
	)

	// A resumed session that copied earlier history before continuing.
	writeJSONL(t, filepath.Join(projects, "-tmp-proj", "sess-b.jsonl"),
		claudeAssistant("sess-b", "a3", claudeTS(0, 12), "msg_2", "req_2", []any{text("Done.")}, usage(3, 7, 0, 1100), nil),
		claudeUser("sess-b", "u7", claudeTS(30, 0), "Now add tests", obj{"origin": obj{"kind": "human"}}),
		claudeAssistant("sess-b", "b1", claudeTS(30, 5), "msg_4", "req_4", []any{text("Added.")}, usage(1, 2, 3, 4), nil),
	)

	// A second config dir with an older transcript format (no origin, string content).
	root2 := t.TempDir()
	writeJSONL(t, filepath.Join(root2, "projects", "-other", "sess-c.jsonl"),
		obj{"type": "user", "uuid": "c1", "sessionId": "sess-c", "timestamp": claudeTS(40, 0), "cwd": "/tmp/other", "version": "1.0.0",
			"message": obj{"role": "user", "content": "Old style prompt"}},
		obj{"type": "assistant", "uuid": "c2", "sessionId": "sess-c", "timestamp": claudeTS(40, 5), "costUSD": 0.5,
			"message": obj{"id": "msg_c", "model": "claude-3-5-sonnet-20241022", "content": []any{text("Hi")}, "usage": obj{"input_tokens": 7, "output_tokens": 8}}},
	)
	return root, root2
}

func TestParseClaudeTranscripts(t *testing.T) {
	root, root2 := writeClaudeFixtures(t)
	t.Setenv("CLAUDE_CONFIG_DIR", root+", "+root2)

	res, err := ParseClaudeTranscripts(ClaudeProjectRoots(), BackfillOptions{})
	require.NoError(t, err)

	assert.Equal(t, 4, res.Files)
	assert.Equal(t, 1, res.BadLines)
	require.Len(t, res.Sessions, 3)

	a := sessionByID(t, res, "sess-a")
	prompts := eventsOfType(a, AICodeEventUserPrompt)
	require.Len(t, prompts, 2)
	assert.Equal(t, "Fix the bug", prompts[0].Prompt)
	assert.Equal(t, 11, *prompts[0].PromptLength)
	assert.Equal(t, "/review PR 12", prompts[1].Prompt)

	requests := eventsOfType(a, AICodeEventApiRequest)
	require.Len(t, requests, 4, "msg_1 once, msg_2 credited to the original session, msg_3, subagent msg_5")
	assert.Equal(t, 50, *requests[0].OutputTokens, "the most complete usage line wins")
	assert.Equal(t, 1000, *requests[0].CacheReadTokens)
	assert.Equal(t, 100, *requests[0].CacheCreationTokens)
	assert.Nil(t, requests[0].CostUSD)
	assert.InDelta(t, 0.01, *requests[1].CostUSD, 1e-9)
	assert.Equal(t, 20, *requests[3].InputTokens, "subagent usage belongs to the parent session")

	apiErrors := eventsOfType(a, AICodeEventApiError)
	require.Len(t, apiErrors, 1)
	assert.Equal(t, "API Error: 529 overloaded", apiErrors[0].Error)
	assert.Empty(t, apiErrors[0].Model)
	assert.Nil(t, apiErrors[0].InputTokens)

	tools := eventsOfType(a, AICodeEventToolResult)
	require.Len(t, tools, 2)
	assert.Equal(t, "Edit", tools[0].ToolName)
	assert.Equal(t, false, *tools[0].Success)
	assert.Nil(t, tools[0].DurationMs)
	assert.Equal(t, map[string]any{"file_path": "/tmp/proj/a.go"}, tools[0].ToolParameters)
	assert.Equal(t, "Bash", tools[1].ToolName)
	assert.Equal(t, true, *tools[1].Success)
	assert.Equal(t, 1234, *tools[1].DurationMs)
	assert.Nil(t, tools[1].ToolParameters, "commands are never uploaded")

	for _, e := range a.Events {
		assert.Equal(t, AICodeClientClaudeCode, e.ClientType)
		assert.Equal(t, "sess-a", e.SessionID)
		assert.Equal(t, "/tmp/proj", e.Pwd)
		assert.Equal(t, "2.1.0", e.AppVersion)
		assert.Equal(t, "shelltime", e.TeamID)
		assert.Regexp(t, `^bf1:[0-9a-f]{40}$`, e.EventID)
	}
	assert.Equal(t, time.Date(2026, 9, 10, 10, 0, 0, 0, time.UTC), a.Start.UTC())

	b := sessionByID(t, res, "sess-b")
	assert.Len(t, eventsOfType(b, AICodeEventApiRequest), 1, "copied history is not counted twice")
	assert.Len(t, eventsOfType(b, AICodeEventUserPrompt), 1)

	c := sessionByID(t, res, "sess-c")
	require.Len(t, c.Events, 2)
	assert.Equal(t, "Old style prompt", eventsOfType(c, AICodeEventUserPrompt)[0].Prompt)
	cReq := eventsOfType(c, AICodeEventApiRequest)[0]
	assert.InDelta(t, 0.5, *cReq.CostUSD, 1e-9)
	assert.Equal(t, 0, *cReq.CacheReadTokens)
	assert.Equal(t, "/tmp/other", cReq.Pwd)
	assert.Equal(t, "1.0.0", cReq.AppVersion)
}

func TestParseClaudeTranscriptsIDsDoNotDependOnSession(t *testing.T) {
	root, root2 := writeClaudeFixtures(t)
	res, err := ParseClaudeTranscripts([]string{filepath.Join(root, "projects"), filepath.Join(root2, "projects")}, BackfillOptions{})
	require.NoError(t, err)

	ids := map[string]bool{}
	for _, s := range res.Sessions {
		for _, e := range s.Events {
			assert.False(t, ids[e.EventID], "duplicate event id %s", e.EventID)
			ids[e.EventID] = true
		}
	}
	assert.True(t, ids[backfillEventID(AICodeClientClaudeCode, "api:msg_2:req_2")])
	assert.True(t, ids[backfillEventID(AICodeClientClaudeCode, "prompt:u1")])
	assert.True(t, ids[backfillEventID(AICodeClientClaudeCode, "tool:toolu_1")])
}

func TestParseClaudeTranscriptsNoPrompts(t *testing.T) {
	root, _ := writeClaudeFixtures(t)
	res, err := ParseClaudeTranscripts([]string{filepath.Join(root, "projects")}, BackfillOptions{NoPrompts: true})
	require.NoError(t, err)

	prompts := eventsOfType(sessionByID(t, res, "sess-a"), AICodeEventUserPrompt)
	require.Len(t, prompts, 2)
	assert.Empty(t, prompts[0].Prompt)
	assert.Equal(t, 11, *prompts[0].PromptLength)
}

func TestParseClaudeTranscriptsCapsLongPrompts(t *testing.T) {
	root := t.TempDir()
	long := strings.Repeat("é", backfillMaxPromptBytes)
	writeJSONL(t, filepath.Join(root, "p", "s.jsonl"),
		claudeUser("s", "u1", claudeTS(0, 0), long, obj{"origin": obj{"kind": "human"}}))

	res, err := ParseClaudeTranscripts([]string{root}, BackfillOptions{})
	require.NoError(t, err)

	e := res.Sessions[0].Events[0]
	assert.LessOrEqual(t, len(e.Prompt), backfillMaxPromptBytes)
	assert.True(t, strings.HasPrefix(long, e.Prompt))
	assert.Equal(t, backfillMaxPromptBytes, *e.PromptLength, "the length reports the full prompt")
}

func TestClaudeProjectRootsDefaults(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("CLAUDE_CONFIG_DIR", "")
	t.Setenv("XDG_CONFIG_HOME", "")

	assert.Equal(t, []string{
		filepath.Join(home, ".config", "claude", "projects"),
		filepath.Join(home, ".claude", "projects"),
	}, ClaudeProjectRoots())
}
